---
roles:
  - name: geerlingguy.apache
    version: "4.0.0"

  - name: geerlingguy.mysql
    version: "5.0.0"
    
  - name: geerlingguy.php
    version: "6.0.0"
    
  - name: geerlingguy.php-mysql
    version: "2.1.0"
    
  - name: geerlingguy.firewall
    version: "2.6.0"
