apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
     maxUnavailable: 1
     maxSurge: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-container
        image: nginx:1.26.3
        ports:
        - containerPort: 80
        volumeMounts: 
            - name: config-vol
              mountPath: /usr/share/nginx/html/
      volumes:
      - name: config-vol
        configMap:
          name: index-nginx-configmap
