# -*- mode: ruby -*-
# vi: set ft=ruby :
require_relative '../provisioning/vbox.rb'
VBoxUtils.check_version('7.1.6')
Vagrant.require_version ">= 2.4.3"

Vagrant.configure("2") do |config|
    config.vm.box = "debian/bookworm64"
    config.vm.box_check_update = false
    config.vm.hostname = "dbserver"
    config.vm.network "private_network", ip: "192.168.56.11", netmask: "24"

    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true
    config.hostmanager.manage_guest = true
    config.vbguest.auto_update = false

    config.vm.provider "virtualbox" do |vb|
	vb.name = "AISI-P0-#{config.vm.hostname}"
	vb.gui = false
	vb.cpus = 1
	vb.memory = 1024
    end

    config.vm.provision "shell", run: "once", path: "provisioning/db.sh"
end
