---
- hosts: cluster
  become: yes

  tasks:
    - name: Update Package Cache
      ansible.builtin.apt:
        update_cache: yes

- name: NFS common config
  ansible.builtin.import_playbook: playbooks/nfs-common.yml

- name: Setup NFS server
  ansible.builtin.import_playbook: playbooks/nfs-server.yml

- name: Setup NFS clients
  ansible.builtin.import_playbook: playbooks/nfs-client.yml
